# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ddf4bf6e3ebd78afb0fd8c99c24c7f82db5cb1cf54bebdc4f07c1e769a090529265e928824a14660b3aa8e1f4f68c800ba2bab297631375afa1437bc4f67f42

test:
  secret_key_base: b833fa405c29402730da2831ea64bd056a9f7bc2e5e4de36a21ff67d54e372777cd3bb5b77959fba773f7ec465a34654d2d90cc4768ea96e1bac3c8df0477609

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
